### ISSUE TITLE
schema-revision: annotationToEntity.schema.json

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/SANDS#28]
1. the `verifiable` property only makes sense to me between user-defined annotations to atlas defined entities
2. even then its not really `verifiable` but just the confirmation/judgment of the curator that needs to be captured here
3. can this be solved differently?

**Comment by UlrikeS91** [comment]
I would remove it all together. Our original thought was to give an estimation for whether or not an user-`annotationToEntity` can be verified as correct by a curator (given in its own curator-`annotationToEntity`). This is mostly a provenance/curation progres tracking thing. I don't think these things should be recorded with SANDS (or at least not with the first version of it). Curators do record the information, and maybe we could make it available in a different way (e.g. as report shared along with the data).

**Comment by lzehl** [comment]
- solved differently now; directly solved in annotation via "definingTerm" and "relatedAtlasTerm" in addition to official terminologies identifiable via their connection to an ontology
