### ISSUE TITLE
schema-revision: brainAtlas.schema.json

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/SANDS#29]
1. should `terminology` be schema or just a property (see below)
2. is the `referenceDataset` not implicitly given by the files of `annotationSet`/`terminology`/`coordinateSpace`?

**Comment by UlrikeS91** [comment]
1. Depends on the answers to issue #31. 
2. A clear yes for me. I would remove it. We could keep it as an optional property, if the others like to keep it though.

**Comment by lzehl** [comment]
Based on the discussion in #27 we should
1) change brainAtlas.schema.json to brainAtlasVersion.schema.json
2) introduce a brainAtlas.schema.json for grouping the different brainAtlasVersion.schema.json
3) need to link between brainAtlasVersion.schema.json (defined connections; e.g. : newVersionOf; alternativeVersionOf)
4) change `version` property to `versionIdentifier`
5) add `changeLog` to properties (free text for what is new changed in this version)

What properties should be in brainAtlas.schema.json ??? 
a) alias
b) fullName
c) description
d) hasVersions

@UlrikeS91 @aeidi89 @blixilla what do you think?

**Comment by lzehl** [comment]
According to the discussion I will implement now the following schema revisions in a PR:

brainAtlasVersion.schema.json:
    alias [expects: free text , count: 1]
    annotationSet [ expects: annotation , count: 1 - n]
    coordinateSpace [expects: coordinateSpace, count: 1]
    fullName [expects: free text, count: 1]
    newVersionOf [expects: brainAtlasVersion, count: 0 - n]
    alternativeVersionOf [expects: brainAtlasVersion, count: 0 - n]
    referenceDataset [expects: dataset | datasetVersion, count: 1]
    relatedOntology [expects: uri, count: 0 - 1]
    releaseDate [expects: date, count: 1]
    terminology [expects: terminology, count: 1]
    versionIdentifier [expects: free text, count:1]
    versionInnovation [expects: free text, count: 1]

brainAtlas.schema.json:
    alias [expects: free text , count: 1]
    description [ expects: free text , count: 1]
    fullName [expects: free text, count: 1]
    hasVersions [expects: brainAtlasVersion, count: 1 - n]
    referenceProject [expects: project, count: 0 - n]

**Comment by lzehl** [comment]
done in #51
