### ISSUE TITLE
Fixing malformed json & fixing refs to sands-internal, accepting PR?

### ISSUE THREAD

**Issue by xgui3783** [HumanBrainProject/SANDS#43]
Hi all,

Whilst browsing through the repo, I came across a few malformed JSON & reference to sands-internal (e.g. https://github.com/HumanBrainProject/SANDS/blob/master/v0.1/core/coordinateSpace.schema.json#L42)

Are you currently accepting PR to fix minor issues like this?

**Comment by lzehl** [comment]
Thanks for bringing it up :+1: We are aware. I'm fixing it asap.

**Comment by lzehl** [comment]
@xgui3783 I've created PR fixing the malformed JSON & references to sands-internal.

Sorry that I overlooked your last point: YES we do accept PRs that are fixing such issues. 
We are very happy for feedback and support :smiley:
